### ISSUE TITLE
Errors when running the README example

### ISSUE THREAD

**Issue by ag-TJNII** [specht/neo4j_bolt#1]
$ gem list | grep -i neo4j_bolt
neo4j_bolt (0.1.19)

While trying to run the README examples none of the active methods are working.

Setting up the gem works as documented:
```
[1] pry(main)> require 'neo4j_bolt'
=> true
[2] pry(main)> Neo4jBolt.bolt_host = 'localhost'
=> "localhost"
[3] pry(main)> Neo4jBolt.bolt_port = 7687
=> 7687
```

However there appears to be a gap between https://github.com/specht/neo4j_bolt#connecting-to-a-neo4j-database and https://github.com/specht/neo4j_bolt#running-queries.  The neo4j query example doesn't have a module namespace:

```
[4] pry(main)> entries = neo4j_query("MATCH (n) RETURN n;")
NoMethodError: undefined method `neo4j_query' for main:Object
from (pry):4:in `__pry__'
```

It also doesn't appear to be a module method:

```
[5] pry(main)> entries = Neo4jBolt.neo4j_query("MATCH (n) RETURN n;")
NoMethodError: undefined method `neo4j_query' for Neo4jBolt:Module
from (pry):5:in `__pry__'
```

The disconnect example doesn't work either:

```
[6] pry(main)> Neo4jBolt::cleanup_neo4j
NoMethodError: undefined method `cleanup_neo4j' for Neo4jBolt:Module
from (pry):6:in `__pry__'
```

Is this supposed to be used as a mixin in another class?

**Comment by specht** [comment]
Yes, it's supposed to be used as a mixin. Sorry for not clarifying this, I'll update the documentation or provide a working example. 

```
class Neo4jGlobal
    include Neo4jBolt
end

neo4j = Neo4jGlobal.new

# use neo4j however you like...
```
